"""Add financial analyst tables

Revision ID: 0454b6eeb73d
Revises: 4de7c201c88f
Create Date: 2026-07-12 14:22:32.217613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0454b6eeb73d'
down_revision: Union[str, Sequence[str], None] = '4de7c201c88f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # (Removed drop_table commands for unmerged tables)
    op.add_column('expenses', sa.Column('vehicle_id', sa.Integer(), nullable=False))
    op.add_column('expenses', sa.Column('category', sa.String(length=50), nullable=False))
    op.add_column('expenses', sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('expenses', sa.Column('expense_date', sa.Date(), nullable=False))
    op.add_column('expenses', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('expenses', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('expenses', 'description',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.create_foreign_key(None, 'expenses', 'vehicles', ['vehicle_id'], ['id'], ondelete='CASCADE')
    op.drop_column('expenses', 'date')
    op.drop_column('expenses', 'type')
    op.drop_column('expenses', 'cost')
    op.add_column('fuel_logs', sa.Column('trip_id', sa.Integer(), nullable=False))
    op.add_column('fuel_logs', sa.Column('fuel_date', sa.Date(), nullable=False))
    op.add_column('fuel_logs', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('fuel_logs', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('fuel_logs', 'liters',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('fuel_logs', 'cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.create_foreign_key(None, 'fuel_logs', 'trips', ['trip_id'], ['id'], ondelete='CASCADE')
    op.drop_column('fuel_logs', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel_logs', sa.Column('date', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'fuel_logs', type_='foreignkey')
    op.alter_column('fuel_logs', 'cost',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('fuel_logs', 'liters',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('fuel_logs', 'updated_at')
    op.drop_column('fuel_logs', 'created_at')
    op.drop_column('fuel_logs', 'fuel_date')
    op.drop_column('fuel_logs', 'trip_id')
    op.add_column('expenses', sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('expenses', sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('expenses', sa.Column('date', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.alter_column('expenses', 'description',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    op.drop_column('expenses', 'updated_at')
    op.drop_column('expenses', 'created_at')
    op.drop_column('expenses', 'expense_date')
    op.drop_column('expenses', 'amount')
    op.drop_column('expenses', 'category')
    op.drop_column('expenses', 'vehicle_id')
    op.create_table('driver_documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('driver_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('issue_date', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('expiry_date', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('file_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('driver_documents_driver_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('driver_documents_pkey'))
    )
    op.create_index(op.f('ix_driver_documents_id'), 'driver_documents', ['id'], unique=False)
    op.create_index(op.f('ix_driver_documents_document_code'), 'driver_documents', ['document_code'], unique=True)
    op.create_table('maintenance',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('service_date', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('cost', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('cancelled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('maintenance_vehicle_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('maintenance_pkey'))
    )
    op.create_index(op.f('ix_maintenance_id'), 'maintenance', ['id'], unique=False)
    op.create_table('maintenance_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('maintenance_logs_vehicle_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('maintenance_logs_pkey'))
    )
    op.create_index(op.f('ix_maintenance_logs_id'), 'maintenance_logs', ['id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('incident_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('driver_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('date', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('score_impact', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('incidents_driver_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('incidents_pkey'))
    )
    op.create_index(op.f('ix_incidents_incident_code'), 'incidents', ['incident_code'], unique=True)
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    # ### end Alembic commands ###
