"""unique_trip_fuel_log

Revision ID: 3f8d305ce750
Revises: d7350ac6b4ce
Create Date: 2026-07-12 15:32:51.413416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f8d305ce750'
down_revision: Union[str, Sequence[str], None] = 'd7350ac6b4ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_incident_code'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_maintenance_logs_id'), table_name='maintenance_logs')
    op.drop_table('maintenance_logs')
    op.drop_index(op.f('ix_driver_documents_document_code'), table_name='driver_documents')
    op.drop_index(op.f('ix_driver_documents_id'), table_name='driver_documents')
    op.drop_table('driver_documents')
    op.create_unique_constraint(None, 'fuel_logs', ['trip_id'])
    op.drop_column('maintenance', 'updated_at')
    op.drop_column('maintenance', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('maintenance', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'fuel_logs', type_='unique')
    op.create_table('driver_documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('driver_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('issue_date', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('expiry_date', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('file_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('driver_documents_driver_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('driver_documents_pkey'))
    )
    op.create_index(op.f('ix_driver_documents_id'), 'driver_documents', ['id'], unique=False)
    op.create_index(op.f('ix_driver_documents_document_code'), 'driver_documents', ['document_code'], unique=True)
    op.create_table('maintenance_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('maintenance_logs_vehicle_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('maintenance_logs_pkey'))
    )
    op.create_index(op.f('ix_maintenance_logs_id'), 'maintenance_logs', ['id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('incident_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('driver_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('date', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('score_impact', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('incidents_driver_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('incidents_pkey'))
    )
    op.create_index(op.f('ix_incidents_incident_code'), 'incidents', ['incident_code'], unique=True)
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    # ### end Alembic commands ###
