"""Add missing vehicle and driver columns

Revision ID: f840d823d71f
Revises: fd7e50c51cf9
Create Date: 2026-07-12 13:04:48.662665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f840d823d71f'
down_revision: Union[str, Sequence[str], None] = 'fd7e50c51cf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_incident_code'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_maintenance_logs_id'), table_name='maintenance_logs')
    op.drop_table('maintenance_logs')
    op.drop_index(op.f('ix_fuel_logs_id'), table_name='fuel_logs')
    op.drop_table('fuel_logs')
    op.drop_index(op.f('ix_driver_documents_document_code'), table_name='driver_documents')
    op.drop_index(op.f('ix_driver_documents_id'), table_name='driver_documents')
    op.drop_table('driver_documents')
    op.alter_column('drivers', 'license_expiry_date',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Date(),
               existing_nullable=False,
               postgresql_using='license_expiry_date::date')
    op.alter_column('drivers', 'contact_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('drivers', 'safety_score',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=5, scale=2),
               nullable=True)
    op.drop_index(op.f('ix_drivers_driver_code'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_license_number'), table_name='drivers')
    op.create_unique_constraint(None, 'drivers', ['license_number'])
    op.drop_column('drivers', 'driver_code')
    op.drop_column('drivers', 'avatar_color')
    op.add_column('trips', sa.Column('trip_number', sa.String(length=50), nullable=False))
    op.add_column('trips', sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('trips', sa.Column('initial_odometer', sa.Integer(), nullable=True))
    op.add_column('trips', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('trips', sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('trips', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('trips', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('trips', 'cargo_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('trips', 'planned_distance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('trips', 'final_odometer',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('trips', 'fuel_consumed',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.drop_index(op.f('ix_trips_trip_code'), table_name='trips')
    op.create_index(op.f('ix_trips_trip_number'), 'trips', ['trip_number'], unique=True)
    op.drop_column('trips', 'trip_code')
    op.add_column('vehicles', sa.Column('vehicle_type', sa.String(length=100), nullable=False))
    op.alter_column('vehicles', 'max_load_capacity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('vehicles', 'odometer',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('vehicles', 'acquisition_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               nullable=True)
    op.drop_column('vehicles', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.alter_column('vehicles', 'acquisition_cost',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('vehicles', 'odometer',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('vehicles', 'max_load_capacity',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('vehicles', 'vehicle_type')
    op.add_column('trips', sa.Column('trip_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_trips_trip_number'), table_name='trips')
    op.create_index(op.f('ix_trips_trip_code'), 'trips', ['trip_code'], unique=True)
    op.alter_column('trips', 'fuel_consumed',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('trips', 'final_odometer',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('trips', 'planned_distance',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('trips', 'cargo_weight',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('trips', 'cancelled_at')
    op.drop_column('trips', 'completed_at')
    op.drop_column('trips', 'dispatched_at')
    op.drop_column('trips', 'updated_at')
    op.drop_column('trips', 'initial_odometer')
    op.drop_column('trips', 'revenue')
    op.drop_column('trips', 'trip_number')
    op.add_column('drivers', sa.Column('avatar_color', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('drivers', sa.Column('driver_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'drivers', type_='unique')
    op.create_index(op.f('ix_drivers_license_number'), 'drivers', ['license_number'], unique=True)
    op.create_index(op.f('ix_drivers_driver_code'), 'drivers', ['driver_code'], unique=True)
    op.alter_column('drivers', 'safety_score',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('drivers', 'contact_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('drivers', 'license_expiry_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.create_table('driver_documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('driver_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('issue_date', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('expiry_date', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('file_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('driver_documents_driver_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('driver_documents_pkey'))
    )
    op.create_index(op.f('ix_driver_documents_id'), 'driver_documents', ['id'], unique=False)
    op.create_index(op.f('ix_driver_documents_document_code'), 'driver_documents', ['document_code'], unique=True)
    op.create_table('fuel_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('liters', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('date', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fuel_logs_vehicle_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('fuel_logs_pkey'))
    )
    op.create_index(op.f('ix_fuel_logs_id'), 'fuel_logs', ['id'], unique=False)
    op.create_table('maintenance_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('maintenance_logs_vehicle_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('maintenance_logs_pkey'))
    )
    op.create_index(op.f('ix_maintenance_logs_id'), 'maintenance_logs', ['id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('date', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('trip_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('expenses_trip_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('expenses_pkey'))
    )
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('incident_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('driver_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('date', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('score_impact', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('incidents_driver_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('incidents_pkey'))
    )
    op.create_index(op.f('ix_incidents_incident_code'), 'incidents', ['incident_code'], unique=True)
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    # ### end Alembic commands ###
